Add logic and tests
Atikingi/react2 pull request #1
Opened 2022-11-13 11:17 UTC by Atikingi

Добавлена логика получения списка пользователей, удаление, добавление в избранное, фильтр по избранному.

2022-11-14 08:05 UTC, mrerberg requested changes

2022-11-14 08:05 UTC, mrerberg commented on colors.css
> +:root {
Почему данный файлик не в src? И почему он тут? Ты его скопировал откуда-то?

2022-11-14 08:05 UTC, mrerberg commented on colors.css
> +:root {
Если скопировал откуда-то, почему не подключил импортом?

2022-11-14 08:05 UTC, mrerberg commented on package.json
>      "web-vitals": "^2.1.4"
Этот пакет не нужен

2022-11-14 08:05 UTC, mrerberg commented on src/App.module.css
> +.hr {
В названиях тегов не привязывайся лучше к именам тегов. Изменится класс, изменится и класс

2022-11-14 08:05 UTC, mrerberg commented on src/App.module.css
> +}
Где отступ между классами?

2022-11-14 08:05 UTC, mrerberg commented on src/components/footer/style.module.css
> +    /*flex-direction: column;*/
?

2022-11-14 08:05 UTC, mrerberg commented on src/components/footer/style.module.css
> +@media (max-width: 1280px) {
Медиа-выражения лучше выстраивать в логичной последовательности

380
640
1280

2022-11-14 08:05 UTC, mrerberg commented on src/components/user-avatar/index.tsx
> +  last_name: string;
camelCase

2022-11-14 08:05 UTC, mrerberg commented on src/components/user-avatar/index.tsx
> +      <div style={{ display: imageLoaded ? 'none' : 'block' }}>
Не надо хардкода, через класс и либу classnames

2022-11-14 08:05 UTC, mrerberg commented on src/components/user-avatar/index.tsx
> +          onLoad={() => setImageLoaded(true)}
Мы стараемся не хардкодить ананонимные функции, вынеси в отдельный обработчик. Тип

function someHandler() {}

2022-11-14 08:05 UTC, mrerberg commented on src/components/users-list/index.tsx
> +    dispatch(fetchData() as any);
Почему any?

2022-11-14 08:05 UTC, mrerberg commented on src/components/users-list/index.tsx
> +  const users = useSelector((state: RootState) => getAllUsers(state));
Селекторы лучше описать отдельно, а не вставлять как ананонимные функции. Это делается для декларативности

2022-11-14 08:05 UTC, mrerberg commented on src/store/actions/thunks/app.ts
> +    axios.get(`${API_URL}?results=6`).then(({ data }) => {
Давай не then, а async и wait

2022-11-14 08:05 UTC, mrerberg commented on src/store/actions/thunks/app.ts
> +      data.results.map((user: UserProps) => (user.favorite = false));
mapper данных я бы вынес в отдельную функцию

2022-11-14 08:05 UTC, mrerberg commented on src/store/reducers/app.ts
> +export type StateProps = {
Можно назвать просто State, его правда нужно экспортировать?

2022-11-14 08:05 UTC, mrerberg commented on src/store/reducers/types.ts
> +export type UserProps = {
Разбей объекты на более маленькие типы.

```
type Name = ...;

type Location = ...;

{
  name: Name
}
```

2022-11-14 08:05 UTC, mrerberg commented on src/store/reducers/types.ts
> +export type UserProps = {
Так и типы можно переиспользовать и проще дебажить

2022-11-14 08:05 UTC, mrerberg commented on cypress/e2e/actions.cy.js
> +    const favoriteButton = cy.get('[data-test-id="favorite-button"]');
https://docs.cypress.io/guides/core-concepts/variables-and-aliases#Elements

Алиасы тут будут в тему

2022-11-14 08:05 UTC, mrerberg commented on cypress/e2e/actions.cy.js
> +  it('should be change color then click favorite button', () => {
should change color...

А вообще, лучше не цвет проверять, а выполнение логики.  Например, после добавления карточки в избранное, врубаешь фильтр избранного и смотришь, есть ли нужная карточка

2022-11-14 08:05 UTC, mrerberg commented on cypress/e2e/actions.cy.js
> +  it('should be change color then click favorite button', () => {
А, ты саму эту кнопку смотришь, которая врубает фильтрацию, да?

2022-11-14 08:05 UTC, mrerberg commented on cypress/e2e/actions.cy.js
> +  it('should be added to favorite after click on favorite button', () => {
Почему ты везде добавляешь be? Она не в тему в данных случаях с точки зрения языка

2022-11-14 08:05 UTC, mrerberg commented on cypress/e2e/actions.cy.js
> +    cy.get('[data-test-id="user-card"]').should('have.length', 12);
https://testing-library.com/docs/cypress-testing-library/intro/

Добавляет много полезных функций поисковиков элементов

2022-11-14 08:07 UTC, mrerberg commented on cypress/e2e/actions.cy.js
> +  it('should be change color then click favorite button', () => {
Лучше по тексту понимать, какое у кнопки состояние

2022-11-14 08:52 UTC, Atikingi commented on colors.css
> +:root {
Случайно оставил, удалил

2022-11-14 08:56 UTC, Atikingi commented on package.json
>      "web-vitals": "^2.1.4"
Удалил

2022-11-14 08:58 UTC, Atikingi commented on src/App.module.css
> +.hr {
Исправил

2022-11-14 08:59 UTC, Atikingi commented on src/App.module.css
> +}
Исправил

2022-11-14 09:00 UTC, Atikingi commented on src/components/footer/style.module.css
> +    /*flex-direction: column;*/
Удалил

2022-11-14 09:01 UTC, Atikingi commented on src/components/footer/style.module.css
> +@media (max-width: 1280px) {
Исправил

2022-11-14 09:05 UTC, Atikingi commented on src/components/user-avatar/index.tsx
> +  last_name: string;
Исправил

2022-11-14 09:44 UTC, Atikingi commented on src/components/user-avatar/index.tsx
> +      <div style={{ display: imageLoaded ? 'none' : 'block' }}>
Переделал на classnames

2022-11-14 09:44 UTC, Atikingi commented on src/components/user-avatar/index.tsx
> +          onLoad={() => setImageLoaded(true)}
исправил

2022-11-14 10:23 UTC, Atikingi commented on src/components/users-list/index.tsx
> +  const users = useSelector((state: RootState) => getAllUsers(state));
Уже были описаны, просто не правильно вызывал их. Исправил

2022-11-14 12:34 UTC, Atikingi commented on src/components/users-list/index.tsx
> +    dispatch(fetchData() as any);
Исправил

2022-11-14 12:43 UTC, Atikingi commented on src/store/actions/thunks/app.ts
> +    axios.get(`${API_URL}?results=6`).then(({ data }) => {
Исправил

2022-11-14 12:58 UTC, Atikingi commented on src/store/actions/thunks/app.ts
> +      data.results.map((user: UserProps) => (user.favorite = false));
Исправил

2022-11-14 13:00 UTC, Atikingi commented on src/store/reducers/app.ts
> +export type StateProps = {
Исправил, да экспорт лишний

2022-11-14 13:30 UTC, Atikingi commented on src/store/reducers/types.ts
> +export type UserProps = {
Исправил

2022-11-14 13:38 UTC, Atikingi commented on cypress/e2e/actions.cy.js
> +    const favoriteButton = cy.get('[data-test-id="favorite-button"]');
Добавил

2022-11-14 13:40 UTC, Atikingi commented on cypress/e2e/actions.cy.js
> +  it('should be change color then click favorite button', () => {
Тут я проверяю, что отрабатывает закрашивание, хотелось бы оставить. Логика добавления в избранное есть ниже по коду

2022-11-14 13:41 UTC, Atikingi commented on cypress/e2e/actions.cy.js
> +  it('should be added to favorite after click on favorite button', () => {
Как говорится "О, я из Англии" =) Исправил

2022-11-14 13:45 UTC, Atikingi commented on cypress/e2e/actions.cy.js
> +    cy.get('[data-test-id="user-card"]').should('have.length', 12);
Спасибо, буду иметь ее ввиду. Для моих тестов думаю уже лишнее ее еще добавлять.

2022-11-14 14:05 UTC, mrerberg requested changes

2022-11-14 14:05 UTC, mrerberg commented on cypress/e2e/actions.cy.js
> +    cy.get('@switchButton').first().click({ force: true });
Почему force клики?

2022-11-14 14:05 UTC, mrerberg commented on cypress/e2e/actions.cy.js
> +    cy.get('[data-test-id="favorite-button"]').as('favoriteButton');
Все же добавь ту либу, которую я говорил, гораздо краше код станет. Заодно, будешь иметь ее апи в виду. Мы ее используем

2022-11-14 14:05 UTC, mrerberg commented on cypress/e2e/actions.cy.js
> +    cy.wait('@getUsers');
А ты мокал ответ для данного вызова? Что тебе прилетает сюда в виде данных?

2022-11-14 14:05 UTC, mrerberg commented on cypress/e2e/render-users.cy.js
> +describe('render users from API', () => {
Почему у файлов расширение js?

2022-11-14 14:05 UTC, mrerberg commented on src/App.tsx
> +      <UserFilter />
Просто Filters? User лишняя приписка

2022-11-14 14:05 UTC, mrerberg commented on src/components/header/index.tsx
> +      <a href='/react-alfa'>
/

Такого пути не достаточно?

2022-11-14 14:05 UTC, mrerberg commented on src/components/header/index.tsx
> +        Test work for Alfa-bank
Test project. Придирка

2022-11-14 14:05 UTC, mrerberg commented on src/components/header/index.tsx
> +          width={200}
А height?

2022-11-14 14:05 UTC, mrerberg commented on src/components/user-avatar/index.tsx
> +        <Loader />
Вместо display: none лучше так

```tsx
if(!imageLoaded) {
  return   <div className={styles.avatarWrapper}>
      <div className={loaderWrapperClass}>
        <Loader />
      </div>
    </div>
}


 return (
    <div className={styles.avatarWrapper}>
      <div className={imageWrapperClass}>
        <img
          className={styles.avatar}
          src={avatar}
          alt={`${firstName} ${lastName}`}
          onLoad={imageLoadedHandler}
        />
      </div>
    </div>
  );
```

2022-11-14 14:05 UTC, mrerberg commented on src/components/user-avatar/index.tsx
> +        <Loader />
Так нагляднее, когда flow разделяются. Загрузка, ошибка, успех

2022-11-14 14:05 UTC, mrerberg commented on src/components/user-avatar/index.tsx
> +  const imageLoadedHandler = () => {
handleImageLoad. Просто и лаконично. Придирка

2022-11-14 14:05 UTC, mrerberg commented on src/components/user-card/index.tsx
> +      <AiTwotoneDelete
Так же можно title добавить. Вообще, при тестировании мы стараемся использовать что-то более нативное (близкое к пользователю), нежели data-test-id. Тут, например, можно использовать title. Это и пользователю подсказка при наведении, и при тестировании можно юзать

2022-11-14 14:05 UTC, mrerberg commented on src/components/user-card/index.tsx
> +        className={isFavorite ? styles.starActive : styles.star}
classnames либа

2022-11-14 14:05 UTC, mrerberg commented on src/components/user-filter/index.tsx
> +    dispatch(clearData());
Почему бы не вызывать clearData внутри fetchData?

2022-11-14 14:05 UTC, mrerberg commented on src/components/user-info/index.tsx
> +  text: string | number;
Текст с числовым типом?

2022-11-14 14:05 UTC, mrerberg commented on src/components/users-list/index.tsx
> +      className={isLoading ? styles.loader : styles.container}
classnames

2022-11-14 14:05 UTC, mrerberg commented on src/components/users-list/index.tsx
> +        <Spinner visible={true} size="m" data-test-id="loader" />
Лучше делать не через тернарник, а как я показывал в одном из своих комментов

```tsx
if(loading) ...

...
```

2022-11-14 14:05 UTC, mrerberg commented on src/store/reducers/app.ts
> +type StateProps = {
Просто State

2022-11-14 14:05 UTC, mrerberg commented on src/store/store.tsx
> +import {AnyAction, combineReducers, configureStore, ThunkAction} from '@reduxjs/toolkit';
Через prettier прогонял весь проект?

2022-11-14 16:45 UTC, Atikingi commented on src/App.tsx
> +      <UserFilter />
Исправил

2022-11-14 16:46 UTC, Atikingi commented on src/components/header/index.tsx
> +      <a href='/react-alfa'>
думаю да

2022-11-14 16:46 UTC, Atikingi commented on src/components/header/index.tsx
> +        Test work for Alfa-bank
Исправил

2022-11-14 16:47 UTC, Atikingi commented on src/components/header/index.tsx
> +          width={200}
Добавил

2022-11-14 17:23 UTC, Atikingi commented on src/components/user-avatar/index.tsx
> +        <Loader />
Согласен, что так выглядит лучше, но есть проблема. У меня в начале стейт false, и он меняется на trueтогда когда загрузится картинка, но если я ставлю условие !mageLoaded, то у меня загружается лоадер, а до сама картинка не начинает загружаться, т.к. не рендерится блок с ней, поэтому и сделал через скрытие элемента. Скорее всего просто не понимаю, как правильно сделать.

2022-11-14 17:23 UTC, Atikingi commented on src/components/user-avatar/index.tsx
> +  const imageLoadedHandler = () => {
Исправил

2022-11-14 17:25 UTC, Atikingi commented on src/components/user-card/index.tsx
> +      <AiTwotoneDelete
Добавил

2022-11-14 17:27 UTC, Atikingi commented on src/components/user-card/index.tsx
> +        className={isFavorite ? styles.starActive : styles.star}
Исправил

2022-11-14 17:29 UTC, Atikingi commented on src/components/user-filter/index.tsx
> +    dispatch(clearData());
Согласен

2022-11-14 17:31 UTC, Atikingi commented on src/components/user-info/index.tsx
> +  text: string | number;
Исправил

2022-11-14 17:34 UTC, Atikingi commented on src/components/users-list/index.tsx
> +      className={isLoading ? styles.loader : styles.container}
Исправил

2022-11-14 17:40 UTC, Atikingi commented on src/components/users-list/index.tsx
> +        <Spinner visible={true} size="m" data-test-id="loader" />
А вот здесь сработало. Исправил

2022-11-14 17:40 UTC, Atikingi commented on src/store/reducers/app.ts
> +type StateProps = {
Исправил

2022-11-14 17:52 UTC, Atikingi commented on src/store/store.tsx
> +import {AnyAction, combineReducers, configureStore, ThunkAction} from '@reduxjs/toolkit';
Прогнал еще раз

2022-11-14 19:10 UTC, Atikingi commented on cypress/e2e/actions.cy.js
> +    cy.get('@switchButton').first().click({ force: true });
Исправил

2022-11-14 19:10 UTC, Atikingi commented on cypress/e2e/actions.cy.js
> +    cy.get('[data-test-id="favorite-button"]').as('favoriteButton');
Добавил, переписал не нее

2022-11-14 19:11 UTC, Atikingi commented on cypress/e2e/actions.cy.js
> +    cy.wait('@getUsers');
Я не правильно понял работу этой команды, по сути она мне не нужна пока, убрал везде

2022-11-14 19:11 UTC, Atikingi commented on cypress/e2e/render-users.cy.js
> +describe('render users from API', () => {
Исправил

2022-11-14 19:13 UTC, Atikingi commented on cypress/e2e/actions.cy.js
> +    cy.get('[data-test-id="favorite-button"]').as('favoriteButton');
Но кнопки удалить и добавить все равно получаю по testId. Они not visible элементы и я не могу получить их по чему-то другому. Возможно из-за того, что они postion:absolute.

2022-11-15 07:36 UTC, mrerberg commented on cypress/e2e/actions.cy.js
> +    cy.wait('@getUsers');
Вообще, она нужна. Ты должен прерывать реальный запрос и мокать его заранее подготовленными данными.

2022-11-15 07:44 UTC, mrerberg requested changes

2022-11-15 07:44 UTC, mrerberg commented on cypress/e2e/actions.cy.ts
> +  it('should delete card then click delete button', () => {
should delete card when delete button was clicked

2022-11-15 07:44 UTC, mrerberg commented on cypress/e2e/actions.cy.ts
> +    cy.findAllByTestId('delete').as('deleteButton');
Тебе не обязательно искать все, функционал достаточно проверять на 1 карточке

2022-11-15 07:44 UTC, mrerberg commented on cypress/e2e/actions.cy.ts
> +    cy.findByText('Show all').as('switchToAllButton');
cy.findByText('Show all').click();

Алиас тут не нужен, избыточек

2022-11-15 07:44 UTC, mrerberg commented on src/components/user-avatar/index.tsx
> +        <Loader />
Я показал для наглядности. Тебе можно отслеживать не состояние конечной загрузки, а грузится ли в данный момент. Получается, в onLoad полетит хенлер, который выставит isLoading в false

2022-11-15 09:33 UTC, Atikingi commented on cypress/e2e/actions.cy.ts
> +  it('should delete card then click delete button', () => {
Исправил

2022-11-15 09:40 UTC, Atikingi commented on cypress/e2e/actions.cy.ts
> +    cy.findAllByTestId('delete').as('deleteButton');
Тогда ругается, что элементов с таким id много

2022-11-15 09:41 UTC, Atikingi commented on cypress/e2e/actions.cy.ts
> +    cy.findByText('Show all').as('switchToAllButton');
убрал

2022-11-15 09:47 UTC, merged